version: "1.1"

services:
  java_app:
    container_name: java_app
    image: url-shortener
    build: .
    ports:
      - 9000:9000
    environment:
      - db_name=User_Java
      - db_pass=java123