version: "1.0"

services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=mongodb+srv://User_Java:java123@cluster0.8ojz2.mongodb.net/url-shortener?retryWrites=true&w=majority
      - DATABASE_USERNAME=url-shortener
      - DATABASE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration